### ISSUE TITLE
Optimize sorting on timestamp custom meta field for Big Data sets

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#280]
Case
Custom Post Type: Users (25.000 records)
FIeld: Joining_date (timestamp)
Columns: Custom Meta, format = date

Gives 500 error on sorting.

**Comment by DGStefan** [comment]
Reevaluate in upcoming release

**Comment by ghost** [comment]
Is this issue resolved in the current release ?

**Comment by DGStefan** [comment]
@niravmehta9 
This issue was closed a long time ago.
But based on your comment, it seems that you still have a problem with sorting on a large dataset?
Do you have this issue on this specific custom field column with field type set to date?
