### ISSUE TITLE
"Lite" versions and add-ons are not supported

### ISSUE THREAD

**Issue by davidmosterd** [codepress/admin-columns-issues#729]
A "Lite" version of a plugin can cause the add-on think a dependency is not met.

ACF can be shipped along with a theme. But our checks expect the 'regular' installed ACF plugin.

Depedency should therefore be checked on a level of checking for functions, classes or constants over paths/ basenames.

**Comment by tobiasschutter** [comment]
fixed by https://github.com/codepress/codepress-admin-columns/commit/c3ce9605082c20de67d5d8873fc6a52a5497b408

**Comment by DGStefan** [comment]
Issue still exists when ACF Lite is loaded through a theme
@tobiasschutter ask me for a theme example to reproduce this.

**Comment by tobiasschutter** [comment]
`after_setup_theme` is used now
